---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: https://api.vercel.com/v1/integrations/deploy/prj_FIg1uhXyNVzv2GbAiU6hutLuAF0k/g9FcnJwp8D 
sections:
- type: heading
  label: BOOKS
- type: heading
  label: Content
- type: directory
  path: docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - documentation-page
- type: heading
  label: Settings
- type: document
  path: data/settings.json
  label: Menu
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  production_output_directory: dist
  install_dependencies_command: yarn
  production_docker_image: node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_prroduction_command: yarn install
